# Generated by Django 5.0.4 on 2024-04-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
