# файл statistics/models.py

from django.db import models
from django.contrib.gis.geoip2 import GeoIP2

class Country(models.Model):
    name = models.CharField(max_length=255)

class Click(models.Model):
    sub_id = models.CharField(max_length=255, blank=True, null=True)
    date_and_time = models.DateTimeField(auto_now_add=True)
    lead = models.BooleanField(default=False)
    sale = models.BooleanField(default=False)
    ip = models.GenericIPAddressField()
    camp_id = models.IntegerField(blank=True, null=True)
    flow_id = models.IntegerField(blank=True, null=True)
    landing_page = models.CharField(max_length=255, blank=True, null=True)
    offer = models.CharField(max_length=255, blank=True, null=True)
    source = models.CharField(max_length=255, blank=True, null=True)
    affiliate_network = models.CharField(max_length=255, blank=True, null=True)
    country_flag = models.CharField(max_length=255, blank=True, null=True)
    state_region = models.CharField(max_length=255, blank=True, null=True)
    bot = models.BooleanField(default=False)
    unique_clicks_campaign = models.IntegerField(blank=True, null=True)
    destination = models.CharField(max_length=255, blank=True, null=True)
    campaign = models.CharField(max_length=255, blank=True, null=True)
    campaign_group = models.CharField(max_length=255, blank=True, null=True)
    landing_page_group = models.CharField(max_length=255, blank=True, null=True)
    offer_group = models.CharField(max_length=255, blank=True, null=True)
    flow = models.CharField(max_length=255, blank=True, null=True)
    site = models.CharField(max_length=255, blank=True, null=True)
    x_requested_with = models.CharField(max_length=255, blank=True, null=True)
    search_engine = models.CharField(max_length=255, blank=True, null=True)
    referrer = models.CharField(max_length=255, blank=True, null=True)
    keyword = models.CharField(max_length=255, blank=True, null=True)
    click_id = models.CharField(max_length=255, blank=True, null=True)
    visitor_code = models.CharField(max_length=255, blank=True, null=True)
    campaign_group_id = models.IntegerField(blank=True, null=True)
    offer_group_id = models.IntegerField(blank=True, null=True)
    landing_group_id = models.IntegerField(blank=True, null=True)
    lp_id = models.IntegerField(blank=True, null=True)
    offer_id = models.IntegerField(blank=True, null=True)
    aff_network_id = models.IntegerField(blank=True, null=True)
    ts_id = models.IntegerField(blank=True, null=True)
    ad_campaign_id = models.IntegerField(blank=True, null=True)
    external_id = models.CharField(max_length=255, blank=True, null=True)
    creative_id = models.CharField(max_length=255, blank=True, null=True)
    sub_id_1 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_2 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_3 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_4 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_5 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_6 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_7 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_8 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_9 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_10 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_11 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_12 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_13 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_14 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_15 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_16 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_17 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_18 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_19 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_20 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_21 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_22 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_23 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_24 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_25 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_26 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_27 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_28 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_29 = models.CharField(max_length=255, blank=True, null=True)
    sub_id_30 = models.CharField(max_length=255, blank=True, null=True)
    connection_type = models.CharField(max_length=255, blank=True, null=True)
    mobile_operator = models.CharField(max_length=255, blank=True, null=True)
    isp = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    language = models.CharField(max_length=255, blank=True, null=True)
    device_type = models.CharField(max_length=255, blank=True, null=True)
    user_agent = models.CharField(max_length=255, blank=True, null=True)
    os_logo = models.CharField(max_length=255, blank=True, null=True)
    operational_system = models.CharField(max_length=255, blank=True, null=True)
    os_version = models.CharField(max_length=255, blank=True, null=True)
    browser = models.CharField(max_length=255, blank=True, null=True)
    browser_version = models.CharField(max_length=255, blank=True, null=True)
    device_model = models.CharField(max_length=255, blank=True, null=True)
    browser_logo = models.CharField(max_length=255, blank=True, null=True)
    ip_1_2 = models.CharField(max_length=255, blank=True, null=True)
    ip_1_2_3 = models.CharField(max_length=255, blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    extra_param_1 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_2 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_3 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_4 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_5 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_6 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_7 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_8 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_9 = models.CharField(max_length=255, blank=True, null=True)
    extra_param_10 = models.CharField(max_length=255, blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    month = models.IntegerField(blank=True, null=True)
    week = models.IntegerField(blank=True, null=True)
    weekday = models.IntegerField(blank=True, null=True)
    day = models.IntegerField(blank=True, null=True)
    hour = models.IntegerField(blank=True, null=True)
    day_and_hour = models.CharField(max_length=255, blank=True, null=True)
    lp_click_time = models.DateTimeField(blank=True, null=True)
    unique_clicks_flow = models.IntegerField(blank=True, null=True)
    unique_clicks_global = models.IntegerField(blank=True, null=True)
    empty_referrer = models.BooleanField(default=False)
    using_proxy = models.BooleanField(default=False)
    landing_clicked = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)
    parent_campaign_id = models.IntegerField(blank=True, null=True)
    parent_clicks_subid = models.CharField(max_length=255, blank=True, null=True)
    parent_campaign = models.CharField(max_length=255, blank=True, null=True)
    profitability = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    revenue = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    profit_loss_all = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    revenue_hold = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    revenue_confirmed = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    revenue_rejected = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    upsells = models.IntegerField(blank=True, null=True)
    time_since_lp_click = models.DurationField(blank=True, null=True)

class Filter(models.Model):
    pass