# Generated by Django 5.0.4 on 2024-04-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('partnerPrograms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offer_type', models.CharField(choices=[('html_file', 'HTML File'), ('redirect', 'Redirect'), ('preload', 'Preload'), ('action', 'Action')], default='html_file', max_length=50)),
                ('html_file', models.FileField(blank=True, null=True, upload_to='offers/')),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('preload_url', models.URLField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('404', '404 Not Found'), ('redirect', 'Redirect to another campaign'), ('html', 'Show as HTML')], max_length=50, null=True)),
                ('action_html', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('partner_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerPrograms.partnerprogram')),
            ],
        ),
    ]
