# Generated by Django 5.0.4 on 2024-04-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trafficSources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('traffic_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='trafficSources.trafficsource')),
            ],
        ),
    ]
