from django.db import models

class Filter(models.Model):
    FILTER_TYPES = (
        ('clicks', 'Clicks'),
        ('unique_clicks_flow', 'Unique clicks (flow)'),
        ('bots', 'Bots'),
        ('revenue_hold', 'Revenue (hold)'),
        ('profit_loss_all', 'Profit/Loss (all)'),
        ('lead', 'Lead'),
        ('bot', 'Bot'),
        ('click_id', 'Click ID'),
        ('subid', 'SubId'),
        ('visitor_code', 'Visitor code'),
        ('campaign_group_id', 'Campaign group ID'),
        ('offer_group_id', 'Offer group ID'),
        ('landing_group_id', 'Landing group ID'),
        ('lp_id', 'LP ID'),
        ('offer_id', 'Offer ID'),
        ('aff_network_id', 'Aff. Network ID'),
        ('ts_id', 'TS ID'),
        ('flow_id', 'Flow ID'),
        ('ad_campaign_id', 'Ad Campaign ID'),
        ('external_id', 'External ID'),
        ('creative_id', 'Creative ID'),
        ('sub_id_1', 'Sub ID 1'),
        ('sub_id_2', 'Sub ID 2'),
        ('revenue_rejected', 'Revenue (rejected)'),
        ('revenue_confirmed', 'Revenue (confirmed)'),
        ('revenue', 'Revenue'),
        ('profitability', 'Profitability'),
        ('upsells', 'Upsells'),
        ('campaign', 'Campaign'),
        ('campaign_group', 'Campaign group'),
        ('landing_page_group', 'Landing page group'),
        ('camp_id', 'Camp. ID'),
        ('date_and_time', 'Date and time'),
        ('year', 'Year'),
        ('month', 'Month'),
        ('week', 'Week'),
        ('weekday', 'Weekday'),
        ('day', 'Day'),
        ('hour', 'Hour'),
        ('day_and_hour', 'Day and hour'),
        ('lp_click_time', 'LP click time'),
        ('destination', 'Destination'),
        ('unique_clicks_flow', 'Unique clicks (flow)'),
        ('unique_clicks_campaign', 'Unique clicks (campaign)'),
        ('unique_clicks_global', 'Unique clicks (global)'),
        ('empty_referrer', 'Empty referrer'),
        ('using_proxy', 'Using proxy'),
        ('landing_clicked', 'Landing clicked'),
        ('sale', 'Sale'),
        ('rejected', 'Rejected'),
        ('parent_campaign_id', 'Parent campaign ID'),
        ('parent_clicks_subid', 'Parent clicks SubID'),
        ('parent_campaign', 'Parent campaign'),
        ('offer_group', 'Offer group'),
        ('landing_page', 'Landing page'),
        ('offer', 'Offer'),
        ('affiliate_network', 'Affiliate Network'),
        ('source', 'Source'),
        ('flow', 'Flow'),
        ('site', 'Site'),
        ('x_requested_with', 'X-Requested-With'),
        ('referrer', 'Referrer'),
        ('search_engine', 'Search engine'),
        ('keyword', 'Keyword'),
        ('sub_id_3', 'Sub ID 3'),
        ('sub_id_4', 'Sub ID 4'),
        ('sub_id_5', 'Sub ID 5'),
        ('sub_id_6', 'Sub ID 6'),
        ('sub_id_7', 'Sub ID 7'),
        ('sub_id_8', 'Sub ID 8'),
        ('sub_id_9', 'Sub ID 9'),
        ('sub_id_10', 'Sub ID 10'),
        ('sub_id_11', 'Sub ID 11'),
        ('sub_id_12', 'Sub ID 12'),
        ('sub_id_13', 'Sub ID 13'),
        ('sub_id_14', 'Sub ID 14'),
        ('sub_id_15', 'Sub ID 15'),
        ('sub_id_16', 'Sub ID 16'),
        ('sub_id_17', 'Sub ID 17'),
        ('sub_id_18', 'Sub ID 18'),
        ('sub_id_19', 'Sub ID 19'),
        ('sub_id_20', 'Sub ID 20'),
        ('sub_id_21', 'Sub ID 21'),
        ('sub_id_22', 'Sub ID 22'),
        ('sub_id_23', 'Sub ID 23'),
        ('sub_id_24', 'Sub ID 24'),
        ('sub_id_25', 'Sub ID 25'),
        ('sub_id_26', 'Sub ID 26'),
        ('sub_id_27', 'Sub ID 27'),
        ('sub_id_28', 'Sub ID 28'),
        ('sub_id_29', 'Sub ID 29'),
        ('sub_id_30', 'Sub ID 30'),
        ('connection_type', 'Connection type'),
        ('mobile_operator', 'Mobile operator'),
        ('isp', 'ISP'),
        ('country_flag', 'Country flag'),
        ('country', 'Country'),
        ('state_region', 'State/region'),
        ('city', 'City'),
        ('language', 'Language'),
        ('device_type', 'Device type'),
        ('user_agent', 'User agent'),
        ('os_logo', 'OS Logo'),
        ('operational_system', 'Operational system'),
        ('os_version', 'OS version'),
        ('browser', 'Browser'),
        ('browser_version', 'Browser version'),
        ('device_model', 'Device model'),
        ('browser_logo', 'Browser logo'),
        ('ip', 'IP'),
        ('ip_1_2', 'IP 1.2.*.*'),
        ('ip_1_2_3', 'IP 1.2.3.*'),
        ('cost', 'Cost'),
        ('extra_param_1', 'Extra Param 1'),
        ('extra_param_2', 'Extra Param 2'),
        ('extra_param_3', 'Extra Param 3'),
        ('extra_param_4', 'Extra Param 4'),
        ('extra_param_5', 'Extra Param 5'),
        ('extra_param_6', 'Extra Param 6'),
        ('extra_param_7', 'Extra Param 7'),
        ('extra_param_8', 'Extra Param 8'),
        ('extra_param_9', 'Extra Param 9'),
        ('extra_param_10', 'Extra Param 10'),
        ('unique_clicks_campaign', 'Unique clicks (campaign)'),
        ('unique_clicks_global', 'Unique clicks (global)'),
        ('unique_clicks_percent_campaign', 'Unique clicks % (campaign)'),
        ('unique_clicks_percent_flow', 'Unique clicks % (flow)'),
        ('unique_clicks_percent_global', 'Unique clicks % (global)'),
        ('bot_percent', 'Bot %'),
        ('proxies', 'Proxies'),
        ('empty_referrers', 'Empty referrers'),
        ('conversions', 'Conversions'),
        ('leads', 'Leads'),
        ('sales', 'Sales'),
        ('rejected', 'Rejected'),
        ('approve_percent', 'Approve %'),
        ('profit_loss_confirmed', 'Profit/Loss (confirmed)'),
        ('cr_conversion_rate', 'CR — Conversion rate'),
        ('crs_sales_conversion_rate', 'CRs (sales) — Conversion rate'),
        ('cr_hold_conversion_rate', 'CR (hold) — Conversion rate'),
        ('roi_all', 'ROI (all)'),
        ('roi_confirmed', 'ROI (confirmed)'),
        ('epc_all_earnings_per_click', 'EPC (all) — Earnings per click'),
        ('uepc_all_earnings_per_unique_click', 'uEPC (all) — Earnings per unique click'),
        ('epc_hold_earnings_per_click', 'EPC (hold) — Earnings per click'),
        ('uepc_hold_earnings_per_unique_click', 'uEPC (hold) — Earnings per unique click'),
        ('epc_confirmed_earnings_per_click', 'EPC (confirmed) — Earnings per click'),
        ('uepc_confirmed_earnings_per_unique_click', 'uEPC (confirmed) — Earnings per unique click'),
        ('cps_cost_per_sale', 'CPS — Cost per sale'),
        ('cpl_cost_per_lead', 'CPL — Cost per lead'),
        ('cpa_cost_per_conversion', 'CPA — Cost per conversion'),
        ('cpc_cost_per_click', 'CPC — Cost per click'),
        ('ucpc_cost_per_unique_click', 'uCPC — Cost per unique click'),
        ('ecpc_cost_per_1000_clicks', 'eCPC — Cost per 1000 clicks'),
        ('ecpm_all_profit_per_1k_clicks', 'eCPM (all) — Profit per 1k clicks'),
        ('ecpm_confirmed_profit_per_1k_clicks', 'eCPM (confirmed) — Profit per 1k clicks'),
        ('ec_all_earnings_per_conversion', 'EC (all) — Earnings per conversion'),
        ('ec_confirmed_earning_per_conversion', 'EC (confirmed) — Earning per conversion'),
        ('time_since_lp_click', 'Time since LP click'),
        ('lp_views', 'LP views'),
        ('lp_clicks', 'LP clicks'),
        ('lp_ctr', 'LP CTR'),
    )
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255, choices=FILTER_TYPES)
    value = models.CharField(max_length=255)